export const indexController = (req, res) => {
    const skills = [
        "Node.js", 
        "Express", 
        "React", 
        "Python", 
        "Flask", 
        "Django", 
        "pandas", 
        "Web Crawling", 
        "HTML5", 
        "CSS3", 
        "TailwindCSS", 
        "Pug", 
        "Sass", 
        "JS/ES6", 
        "React", 
        "GitHub", 
        "AWS", 
        "MongoDB", 
        "RDB/SQL" 
    ];
    const projects = [
        {title:"a", 
        imgUrl:"img/project1.png",
        date: "2021.06.20", 
        skills: ["AWS","GitHub"], 
        description:"hi",
        github:"a",
        website:"a",
        },
        {title:"a", 
        imgUrl:"img/project1.png",
        date: "2021.06.20", 
        skills: ["AWS","GitHub"], 
        description:"hi",
        github:"a",
        website:"a",
        },
        {title:"a", 
        imgUrl:"img/project1.png",
        date: "2021.06.20", 
        skills: ["AWS","GitHub"], 
        description:"hi",
        github:"a",
        website:"a",
        },
        {title:"a", 
        imgUrl:"img/project1.png",
        date: "2021.06.20", 
        skills: ["AWS","GitHub"], 
        description:"hi",
        github:"a",
        website:"a",
        },
        {title:"a", 
        imgUrl:"img/project1.png",
        date: "2021.06.20", 
        skills: ["AWS","GitHub"], 
        description:"hi",
        github:"a",
        website:"a",
        },
        {title:"a", 
        imgUrl:"img/project1.png",
        date: "2021.06.20", 
        skills: ["AWS","GitHub"], 
        description:"hi",
        github:"a",
        website:"a",
        },
    ];
    return res.render("index", {skills, projects});
};