export const indexController = (req, res) => {
    const skills = [
        "Node.js", 
        "Express", 
        "React", 
        "Python", 
        "Flask", 
        "Django", 
        "pandas", 
        "Web Crawling", 
        "HTML5", 
        "CSS3", 
        "TailwindCSS", 
        "Pug", 
        "Sass", 
        "JS/ES6", 
        "React", 
        "GitHub", 
        "AWS", 
        "MongoDB", 
        "RDB/SQL" 
    ];
    const projects = [
        {title:"yongtube", 
        imgUrl:"img/project1.png",
        date: "2021.7", 
        skills: [
            "NodeJS",
            "ES6",
            "Express",
            "Babel",
            "Pug",
            "OAuth 2.0",
            "AJAX",
            "Webpack",
            "SCSS",
            "MongoDB",
            "Mongoose",
            "Multer",
            "ESLint",
            ], 
        description:"Node.js의 프레임워크 Express.js로 유튜브 웹사이트를 구현했습니다. MongoDB로 데이터베이스를 구축하였고, 파일 저장소로 AWS S3를 사용했습니다. Vanilla JS로 동적인 웹사이트를 구현하였습니다. 가입/로그인/로그아웃 기능, Github로 로그인 기능, 비디오 촬영/업로드/수정/삭제/시청, 조회수 기능, 댓글 작성/수정/삭제/읽기 기능 등 핵심적인 기능을 구현하였습니다. ",
        githubUrl:"https://github.com/yjbenkang/yongtube",
        websiteUrl:"https://yongtube.herokuapp.com/",
        },
        {title:"yongflix", 
        imgUrl:"img/project2.png",
        date: "2021.7", 
        skills: [
            "NodeJS",
            "ES6",
            "Express",
            "Babel",
            "Pug",
            "OAuth 2.0",
            "AJAX",
            "Webpack",
            "SCSS",
            "MongoDB",
            "Mongoose",
            "Multer",
            "ESLint",
            ], 
        description:"IMDB 영화 ",
        githubUrl:"https://github.com/yjbenkang/yongtube",
        websiteUrl:"https://yongtube.herokuapp.com/",
        },

    ];
    return res.render("index", {skills, projects});
};